on: push

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    
    - name: authorize-gcloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        
    # name: 'GCP List Clusters '
    - uses: "actions/gcloud/cli@master"
      with:
        args: "container clusters list"
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
