on: push

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    - name: authorize-aws
      uses: actions/aws/cli@master
      with:
        args: "organizations list-accounts"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    # install eb cli
    #- name: install EB CLI using pip (Python 2.7)
     # run: |
     #   python --version
      #  pip --version
     #   pip install awsebcli --upgrade --user
      #  eb --version    
        
  

