on: push

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    
    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        
    - name: authorize-gcloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        
    - name: 'GCP App Describe'
      uses: "actions/gcloud/cli@master"
      with:
        args: "app describe --project=twilight-pulsar-46"
        
    - name: 'GCP App Deploy'
      uses: "actions/gcloud/cli@master"
      with:
        args: "app deploy ~/app.yaml --project=twilight-pulsar-46"
